CREATE TABLE "organizations" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" VARCHAR2(120) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "users" (
  "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "org_id" NUMBER(10) NOT NULL,
  "email" VARCHAR2(255) NOT NULL UNIQUE,
  "role" VARCHAR2(255) NOT NULL DEFAULT 'member' CHECK ("role" IN ('admin', 'member', 'guest')),
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "ix_users_email" ON "users" ("email");

ALTER TABLE "users" ADD CONSTRAINT "fk_users_org" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE;
