import { describe, expect, it } from 'vitest';
import { exportSql } from '../export';
import { buildSampleDiagram } from './sampleModel';

const d = buildSampleDiagram();

describe('SQL export — per-dialect behavior', () => {
  it('postgres: SERIAL, native enum type, double quotes, FK with ON DELETE', () => {
    const sql = exportSql(d, 'postgres');
    expect(sql).toContain('CREATE TYPE "user_role" AS ENUM (\'admin\', \'member\', \'guest\');');
    expect(sql).toContain('"id" SERIAL NOT NULL');
    expect(sql).toContain('"email" VARCHAR(255) NOT NULL UNIQUE');
    expect(sql).toContain('"role" "user_role" NOT NULL DEFAULT \'member\'');
    expect(sql).toContain('ON DELETE CASCADE');
    expect(sql).toContain('CREATE UNIQUE INDEX "ix_users_email" ON "users" ("email")');
  });

  it('mysql: backticks, AUTO_INCREMENT, inline ENUM, ENGINE, inline comment', () => {
    const sql = exportSql(d, 'mysql');
    expect(sql).toContain('`id` INT NOT NULL AUTO_INCREMENT');
    expect(sql).toContain("`role` ENUM('admin', 'member', 'guest')");
    expect(sql).toContain("COMMENT 'login email'");
    expect(sql).toContain(') ENGINE=InnoDB;');
    expect(sql).not.toContain('"id"');
  });

  it('sqlite: INTEGER PRIMARY KEY AUTOINCREMENT inline; enum becomes CHECK', () => {
    const sql = exportSql(d, 'sqlite');
    expect(sql).toContain('"id" INTEGER PRIMARY KEY AUTOINCREMENT');
    expect(sql).not.toMatch(/PRIMARY KEY \("id"\)/); // no separate table-level PK for the auto pk
    expect(sql).toContain('CHECK ("role" IN (\'admin\', \'member\', \'guest\'))');
  });

  it('mssql: [brackets], IDENTITY after type, NVARCHAR, GO batches', () => {
    const sql = exportSql(d, 'mssql');
    expect(sql).toContain('[id] INT IDENTITY(1,1) NOT NULL');
    expect(sql).toContain('[email] NVARCHAR(255) NOT NULL UNIQUE');
    expect(sql).toContain('\nGO\n');
  });

  it('oracle: GENERATED AS IDENTITY, VARCHAR2, NUMBER, no native boolean', () => {
    const sql = exportSql(d, 'oracle');
    expect(sql).toContain('GENERATED BY DEFAULT AS IDENTITY');
    expect(sql).toContain('VARCHAR2(255)');
  });

  it('mariadb: behaves like mysql (backticks + AUTO_INCREMENT)', () => {
    const sql = exportSql(d, 'mariadb');
    expect(sql).toContain('`id` INT NOT NULL AUTO_INCREMENT');
  });

  it('schemaQualified option qualifies table names', () => {
    const sql = exportSql(d, 'postgres', { schemaQualified: true });
    expect(sql).toContain('CREATE TABLE "public"."users"');
  });

  it('inlineForeignKeys places the FK inside CREATE TABLE', () => {
    const inline = exportSql(d, 'postgres', { inlineForeignKeys: true });
    expect(inline).toMatch(/CREATE TABLE[^;]*CONSTRAINT "fk_users_org" FOREIGN KEY/s);
    expect(inline).not.toContain('ALTER TABLE');
  });
});
