/** Oracle — NUMBER/VARCHAR2, 12c+ GENERATED … AS IDENTITY, no native boolean. */
import type { DialectId, Field } from '../../model/types';
import { BaseDialect } from './BaseDialect';
import type { AutoIncrementPlan } from './Dialect';

export class OracleDialect extends BaseDialect {
  readonly id: DialectId = 'oracle';

  protected autoIncrementPosition: 'afterType' | 'afterConstraints' = 'afterType';

  renderAutoIncrement(_field: Field): AutoIncrementPlan {
    return { inlineClause: 'GENERATED BY DEFAULT AS IDENTITY' };
  }
}
